# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeSandbox' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for ReactNativeSandbox


  # Refer: https://github.com/ivpusic/react-native-image-crop-picker#ios
  # this is very important to have!
  rn_path = '../node_modules/react-native'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket'
  ]

  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'


  #target 'ReactNativeSandbox-tvOSTests' do
  #  inherit! :search_paths
  #  # Pods for testing
  #end

  target 'ReactNativeSandboxTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeSandbox-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeSandbox-tvOS

  target 'ReactNativeSandbox-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


# Refer: https://github.com/ivpusic/react-native-image-crop-picker#ios
# very important to have, unless you removed React dependencies for Libraries
# and you rely on Cocoapods to manage it
post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == "React"
      target.remove_from_project
    end
  end
end

